### PR TITLE
[research][s]: Creating folder "research" in "community" repo with some initial thoughts about community living

### LINKED ISSUE #114: Add materials for studying communities life and communities spaces
The key questions explored in this piece are: 

* What does community life look like in Life itself?
* Can we replicate or encapsulate the experience lived by community members to be able to transmit best practices to other community hubs?

To answer these questions, we define and explore the entire phase space* of activities as well as spaces of living areas. It’s only by understanding the whole space in combination with activities that we can identify the key community characteristics.

## Tasks

- [ ] Write method for studying community spaces and documenting community life  
The main document in progress is here https://docs.google.com/document/d/1iEnEU04ZiTpLjhlxp2QlZ9Va9SOymxn3YB-2lADdKcM/edit?usp=sharing 

About the method we develop with M.S. during our stay in Sympoesis #2  . This method for studying communities can be further developed and used in more general contexts such as studies of intentional communities. We define and explore the entire phase space* of activities as well as spaces of living areas. It’s only by understanding the whole space in combination with activities that we can identify the key community characteristics. 
Let me know if any comments are needed. 

- [ ] Integrate this method into other contexts, e.g. for other repos of Life itself ic.org (intentional communities) https://github.com/life-itself/intentional-communities

### PR DESCRIPTION
**Pull request by Liyubov**
This pull request is related to the issue https://github.com/life-itself/community/issues/114 
Fixes #114 
Reply to @rufuspollock on community folder structure dedicated to research ideas

### CODE REVIEW

**Comment by rufuspollock** [comment]
@Liyubov looks good - my one question was re `research/Life Itself Draft Contemplative activism residency 15 November-15 December 2021 DRAFT.pdf`. Do we want the PDF in the repo or could you commit a source version in e.g. markdown (or if editing in word/google docs leave it there and just put a link to it in the readme).

**Comment by Liyubov** [comment]
yes, agreed, maybe google doc link is easiest for editing even though not always. 
i will create another new google document for editing then.

**Comment by Liyubov** [comment]
created the document for sharing and updated the link in README for editing and proposing ideas for the method 
https://docs.google.com/document/d/1wy4fFZ-ympMCR_FeMrWTs_Dz8buWgABRBrVrSj203tE/edit?usp=sharing

**Comment by rufuspollock** [comment]
@Liyubov ok and did you remove the pdf from the pull request?

**Comment by rufuspollock** [comment]
@Liyubov it's in 👏 🙏  Looking forward to many more contributions 😉 Also recommend checking out #89

**Pull request merged**
