### PR TITLE
Upgrade and migration of all pages and assets from Life Itself wordpress

### PR DESCRIPTION
**Pull request by khalilcodes**
### Summary
Tasks from https://github.com/flowershow/flowershow/issues/261

This PR upgrades the site to use the latest flowershow and migrates all the pages and images from life itself's wordpress site to the content folder after. Pages are converted to markdown using the tool from https://github.com/flowershow/wordpress-export-to-markdown-plus

### Tasks
- Transfer all pages with relevant sub directories to `vault/pages` and symlink to `content/pages`
  - Create/modify markdown with html image gallery for some pages
- Transfer blogs from life iteself wordpress to `vault/blogs`
  - Create custom layout for blogs
  - Create custom bloglist component
- Add all images to `vault/assets/images`
- Replace with a new font in docs and blog layouts - Poppins (simple and nice)
- Add tailwind packages - line-clamp and aspect-ratio
- Modify `MDX.js` to add leading slashes to image paths in markdown.
  - *more context in comments section here - https://github.com/flowershow/flowershow/issues/258*

### Page Example Screenshot

@ [pages/imaginary-society](https://deploy-preview-212--zesty-liger-3a5c29.netlify.app/pages/imaginary-society)

Screen Shot 2022-12-05 at 4 54 14 PM

### Blog Example Screenshot

@ [blog/august-wrapped](https://deploy-preview-212--zesty-liger-3a5c29.netlify.app/blog/august-wrapped)

Screen Shot 2022-12-05 at 7 05 00 PM

### CODE REVIEW

**Comment by khalilcodes** [comment]
@olayway I'll add the blog folder in this PR as well.

**Review by olayway — APPROVED** [review]
LGTM :)

**Comment by rufuspollock** [comment]
@khalilcodes well done for the epic effort 👏👏. A few comments though in general i think we can merge and make changes afterwards (can you let me merge please as i need to sync this with others):

- [ ] can you confirm the commands run to do the content migration (in future can you put extensive details of this in the commit message related to the migration). This is so if migration needs to be run again we know what to do. In general having a script of this e.g. in a gist is a good idea.
- [ ] pages content should get symlinked to root of the site i think and this will create issues for e.g. image paths etc if inside `pages` subfolder of vault so think this stuff has to be at the root of the vault ... (need to think a bit about this)
  - [ ]  we need this because we need to have new site have similar url structure to old site e.g. if a page current at lifeitself.org/xyz it can't suddenly be at lifeitself.org/pages/xyz
- [ ] Re images: these should be in vault i think along with the markdown (that way obsidian can be used as an editor) and then symlinked across to `content`. The path in the vault should be same as path on the site so i imagine we add these to `vault/assets/images` and then symlink these into content/images - though perhaps we want a subdirectory.

Minor:

- [ ] as best practice a PR for upgrade and PR for content migration would be cleaner
- [ ] improvements to theme e.g. poppins could be nicer
- [ ] isn't tailwind-aspect-ratio already in core (if not it should be re the youtube stuff no?)

### Aside: re where content is located

Overall there is a question of what content goes in the vault and what goes into `site`. I think it will be confusing to split content except in some special case like front page (??). This is an issue that is about making things work for devs and editors ... (this is something to discuss in an issue i think).

**Comment by khalilcodes** [comment]
@rufuspollock 

* > (can you let me merge please as i need to sync this with others)

  Can do 👍 

* > pages content should get symlinked to root of the site ...

  we can symlink everything in pages folder to root content eg. `ln -s ../../vault/pages/* .` but in this case each file and folder would be an individual symlink and anything new added to pages folder won't be added automatically to content (ie. we would need to symlink the file/folder each time we add one in pages). I think for now we can do this, although I feel that mostly everything in `vault` **_is_** the content folder at this point. 

* > Re images: these should be in vault i think along with the markdown ...

  Yes, I had done this in the next commit along with pages but forgot to update that in the description.

* > as best practice a PR for upgrade and PR for content migration would be cleaner

  Realized this after push 😅 

* > isn't tailwind-aspect-ratio already in core

  I thought so too, but apparently it isn't so added here.

**Comment by khalilcodes** [comment]
@rufuspollock should I merge this or are we looking to move pages to root content in this PR ?

**Pull request closed without merging**
