### PR TITLE
Residencies index page

### PR DESCRIPTION
**Pull request by khalilcodes**
Tasks from #423 

### Summary

This PR refactors the residency index page and adds upcoming residencies list.

### Tasks

* Move `programs/index` to `pages/programs`
* Add upcoming residencies list
* Refactor markdown to jsx
* Fix residency layout and filepath in `contentlayer.config.js`

### Previews

* https://423-residency-index-page.lifeitself-org.pages.dev/programs

### CODE REVIEW

**Comment by rufuspollock** [comment]
@khalilcodes my 2c is that for courses we don't want stacked cards: we want one event per line sorted by date (i.e. next stuff first).

We also want below that (probably) a list of past residencies (it is nice to see what happened before).

**Comment by khalilcodes** [comment]
@rufuspollock 

> We also want below that (probably) a list of past residencies

Previous residencies were just hardcoded same as before since some of them are not in the `content/programs` folder and the ones that are don't have the frontmatter (only title & desc). So kept it as is until updated. Should I make those as a list component too ?

**Comment by rufuspollock** [comment]
> @rufuspollock
> 
> > We also want below that (probably) a list of past residencies
> 
> Previous residencies were just hardcoded same as before since some of them are not in the `content/programs` folder and the ones that are don't have the frontmatter (only title & desc). So kept it as is until updated. Should I make those as a list component too ?

No, let's leave then - this was just a nice idea.

**Comment by rufuspollock** [comment]
@khalilcodes looks good, merging!

**Pull request merged**
