### PR TITLE
Add mailchimp newsletter form

### PR DESCRIPTION
**Pull request by khalilcodes**
Tasks from #307

### Summary

This PR adds lifeitself's mailchimp newsletter signup form in the layout for all pages (except podcast pages).

### Changes
* Create custom components for newsletter - `Newsletter.jsx`, `useMailchimp.js`
  * Add jsonp package (to fetch/post to mailchimp)
* Add Newsletter form component in layout
* Add Mailchimp env variable in Netlify

### Screenshot

Screen Shot 2023-02-08 at 6 27 32 PM

### CODE REVIEW

**Comment by nathenf** [comment]
@khalilcodes if so it looks good to go!

**Comment by khalilcodes** [comment]
@nathenf they do go but can you also test to confirm ?

**Comment by nathenf** [comment]
Screenshot 2023-02-08 at 09 25 28

This comes up right now, but maybe because it isn't live? @khalilcodes

**Comment by khalilcodes** [comment]
@nathenf oh right didn't update the form in mailchimp to remove first name.

**Comment by khalilcodes** [comment]
@nathenf can you test again

**Comment by nathenf** [comment]
@khalilcodes yes this works now!

**Comment by nathenf** [comment]
@khalilcodes we are good to Merge!

**Pull request merged**
