### PR TITLE
Add heading font and theme color

### LINKED ISSUE #181: Theme and front page for next.lifeitself.org
Current default theme of flowershow is not so suited to life itself. We want to revise it.

As well as being important for life itself this is also a chance to learn about how to do theming cleanly for a flowershow based site (and write that up).

## Acceptance

- [ ] "light" theme similar to current site (but need not be identical as probably about to revise look and feel)
  - [x] default to light theme
  - [x] fonts set in tailwind config and for heading fonts we use the special font Restora we were using before (see https://github.com/life-itself/climate/blob/main/site/styles/globals.css for use on climate site in nextjs app) **✅ 2023-01-19 in PR #270** 
     - [x] main body font we can leave for now - what were we using before? nunito sans? **✅2023-01-19 ❌ wontfix**
  - [x] standard (named?) colors set (in tailwdinf.config.js?) and then used in theme (so that easy to changes color later) **✅ 2023-01-19 set secondary to lifeitself yellow theme color so uses eg. "bg-secondary"**
- [x] hero section on front page that resembles current site (no more than hero needed for now as rest will change)
  - [x] Main text
  - [x] Image on RHS
  - [x] Collaborators 
- [x] write up of process of theming (at least hero) etc for flowershow as a tutorial
- [x] Search in navbar **✅ 2023-01-17 Added in commit [60196dc](https://github.com/life-itself/community/commit/60196dc2b36a8703ddb92458005c7e9026c08c2c)** 

## Tasks

- [x] default to light theme for now (so we don't have to wrangle dark them - plus dark/light theme is quite a dev thing that life itself users won't care about i don't think) **✅ 2022-11-06**
- [x] Reproduce (roughly) current hero **✅ 2022-11-06**
- [x] About and Teams page **✅ 2022-11-08**
- [x] Collaborators section **✅ 2022-11-08**
- [x] Add fonts and colors plus quick tutorial write up
- [x] Podcast page - using this tailwind template https://tailwindui.com/templates/transmit

### PR DESCRIPTION
**Pull request by khalilcodes**
Closes #181 
### Summary

This PR changes the heading fonts to Restora (from old lifeitself site) and theme color as a secondary.

### Changes
* create folder for local font files in `public/fonts` (Restora, RestoraBold, RestoraExtraLight)
* Import in `styles/global.css`
* change font-headings in `tailwind.config.js`
* add font-headings to components
* add colors secondary for lifeitself theme yellow eg. `"text-secondary"`

### Screenshot previews
Screen Shot 2023-01-19
Screen Shot 2023-01-19

### CODE REVIEW

**Review by rufuspollock — APPROVED** [review]
LGTM.

**Comment by rufuspollock** [comment]
@khalilcodes it would have been nice to have a couple of links or screenshots (from test deployed site) showing this working on home page and on a markdown page. Could you do that? (and put in the original issue as a comment too).

**Comment by rufuspollock** [comment]
Noticed one small issue: font in navbar is not using it. But i imagine that is hard to fix as navbar is in core ...

**Comment by khalilcodes** [comment]
@rufuspollock 
> But i imagine that is hard to fix as navbar is in core ...

we haven't updated the site to latest flowershow yet, so I was able to change the placeholder to "search" (was "search docs"). Though this is something that needs to be resolved in core.

**Pull request merged**
