### PR TITLE
Projects, Tao, Residencies [xs] - Corrections to syntax and formatting

### PR DESCRIPTION
**Pull request by nathenf**
- Removed spaces in internal links
- Updated a few initiative links
- Changed initiatives index copy from Projects to Initiatives
- Deleted 2 duplicate residency pages
- Improved formatting of Logos page and used correct syntax

### CODE REVIEW

**Comment by nathenf** [comment]
@khalilcodes I just saw your pull request. We may have some conflicts on some pages...

**Comment by khalilcodes** [comment]
@nathenf that's fine, you can merge if all good and I'll update my PR accordingly if needed.

**Comment by nathenf** [comment]
@khalilcodes well the deploy failed, but I can't see why...

**Comment by khalilcodes** [comment]
@nathenf two files were removed from the vault - `conscious-food-workshop.md` and `consious-food-residency.md` and since these were symlinked individually we have to delete them from the `site/content` folder as well.

**Comment by nathenf** [comment]
@rufuspollock should I merge this for now?

**Pull request merged**
