### PR TITLE
🚫 Remove search bar

### LINKED ISSUE #429: Remove header menu search bar
Three issues with header search bar:

1. does not properly index all pages
2. is unresponsive when typing and then makes the page unresponsive
3. Search bar is too long in header menu and is squashing the menu and join the community button. 

## Acceptance

- [x] Header menu looks good with reduce search bar size **✅2023-10-11 ❌**
- [x] Search function works and doesn't make the page unresponsive **✅2023-10-11 ❌**
- [ ] Search functionality removed

## Tasks

- ~[ ] Fix the search bar~
- [ ] Remove search bar

### PR DESCRIPTION
**Pull request by olayway**
Closes #429 

As agreed in the issue comments, this PR removes the search functionality.

### CODE REVIEW

**Comment by rufuspollock** [comment]
@olayway lgtm but note build is failing.

**Review by rufuspollock — APPROVED** [review]
LGTM but build is failing - may be something else? Can we double check and then merge ...

**Comment by olayway** [comment]
I have no idea what the issue might be, but the build fails with the following errors for lots of pages:

```
Error occurred prerendering page "/blog/2022/05/26/life-itself-summer-gathering-2022". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Zc (/Users/o/Projects/community/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:493)
    at Z (/Users/o/Projects/community/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/Users/o/Projects/community/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
    at Z (/Users/o/Projects/community/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/Users/o/Projects/community/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
    at Z (/Users/o/Projects/community/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/Users/o/Projects/community/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
    at Z (/Users/o/Projects/community/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/Users/o/Projects/community/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
    at Z (/Users/o/Projects/community/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
```

Already tried reverting `package.json` to the previous state but didn't work.

**Comment by rufuspollock** [comment]
WONTFIX for now. Let's reopen when we do site upgrade.

**Pull request closed without merging**
